### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Yoshimaster96** [captainsouthbird/3Mix#1]
I think it would be useful to hackers if you included the modified code only, either in another folder or a different repository.

Just a thought.

**Comment by captainsouthbird** [comment]
The problem is that I doubled the PRG banks and moved a lot of functions around from their original position so I could expand upon them. I also completely changed the layout of the RAM space to accommodate saves among other things. Even the music player was changed to support many more banks! Really trying to rationalize it against the SMB3 native source would be far less useful than you might imagine. It's more like you'd be better off learning how the base SMB3 works and then trying to follow the remnant patterns.
